cache:
  paths:
    - build/
stages:
  - release
  - deploy

create:
  image: docker:latest
  stage: release
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
    CI_REGISTRY: registry.gitlab.com
  before_script:
    - docker info
  script:
    - ls -l
    - echo $CI_PROJECT_DIR
    - echo $CI_PROJECT_NAME
    - echo "${CI_REGISTRY_IMAGE}:latest"
  only:
    - master
