cache:
  paths:
    - build_itcrowdhu/
    - build_itnewscloud/
stages:
  - build
  - release
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm i env-cmd -g
    - npm run build:itcrowdhu
    - npm run build:itnewscloud
  only:
    - master

create:
  image: docker:latest
  stage: release
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  before_script:
    - docker info
  script:
    - ls -l
    - echo $CI_PROJECT_DIR
    - echo $CI_PROJECT_NAME
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:itcrowdhu" -f Dockerfile.itcrowdhu .
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:itnewscloud" -f Dockerfile.itnewscloud .
    - docker push "${CI_REGISTRY_IMAGE}:itcrowdhu"
    - docker push "${CI_REGISTRY_IMAGE}:itnewscloud"
  only:
    - master

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - apk add --update --no-cache openssh sshpass
    - sshpass -V
    - export SSHPASS=$DEPLOY_REMOTE_PASSWORD
    - sshpass -e ssh -oStrictHostKeyChecking=no $DEPLOY_REMOTE_USERNAME@$DEPLOY_REMOTE_HOST '$DEPLOY_REMOTE_SCRIPT'
  only:
    - master
